name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libgtk-3-0

      - name: Install Playwright Browsers
        run: |
          npx playwright install

      - name: Build with Maven
        run: mvn clean install

      - name: Run Cucumber Tests
        run: mvn test

      - name: Generate Cucumber Report
        run: mvn verify

      - name: Upload Cucumber Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/
